var rawUserData = {
  "login": "taull",
  "id": 10332666,
  "avatar_url": "https://avatars.githubusercontent.com/u/10332666?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/taull",
  "html_url": "https://github.com/taull",
  "followers_url": "https://api.github.com/users/taull/followers",
  "following_url": "https://api.github.com/users/taull/following{/other_user}",
  "gists_url": "https://api.github.com/users/taull/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/taull/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/taull/subscriptions",
  "organizations_url": "https://api.github.com/users/taull/orgs",
  "repos_url": "https://api.github.com/users/taull/repos",
  "events_url": "https://api.github.com/users/taull/events{/privacy}",
  "received_events_url": "https://api.github.com/users/taull/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Taylor Aull",
  "company": "The Iron Yard",
  "blog": "",
  "location": "United States",
  "email": "aull.taylor@gmail.com",
  "hireable": false,
  "bio": null,
  "public_repos": 13,
  "public_gists": 0,
  "followers": 4,
  "following": 4,
  "created_at": "2014-12-28T19:01:03Z",
  "updated_at": "2015-01-27T16:11:44Z"
}
